categories:
- Sequence Analysis
- RNA
- Statistics
description: Logol is a pattern matching grammar language and a set of tools to search a pattern in a sequence
homepage_url: http://logol.genouest.org/web/app.php/logol
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/logol
type: unrestricted
